# Tinker {#fours-not-fores}

#### Keywords {-}

golf, coaching, wearables, clustering, neural networks

## What is Tinker, and what do we hope to accomplish?

Every year millions of amateur golfers spend countless hours tinkering with their stance, grip, backswing, and swing angle in an attempt to lower their scores on the course. Despite all of this tinkering, these individuals, oftentimes, have no idea what it is that they actually need to correct or how to fix what they have correctly identified as the problem. Valuable time is spent fixing and un-fixing what they have changed, and without proper coaching, practice may do more harm than good. Professional lessons are expensive, and further, the coaching received during these lessons ceases when the lesson ends. Our goal at Tinker is to revolutionize the coaching space and provide the same services that expensive golf lessons provide, at a fraction of the cost, whenever the golfer wants to play.

## How do we plan to accomplish this?

To do this, Tinker uses strategically placed sensors on a golfer's wrists, elbows, shoulders, knees, and ankles (as well as information about the shot's outcome) to analyze the components of a golfer's swing and offer actionable adjustments that they can implement to improve their accuracy, power, and consistency. Every round played, every trip to the driving range, becomes a potential data point that can be used to help the golfer get the absolute most out of his or her practice time. 

Tinker also recognizes that there are multiple ways to get to the same resul. Not all successful swings follows the same club path (nor are positive outcomes defined the same way by golfers of different skill levels). By analyzing the locations of our sensor-targeted areas at the swing's start, midpoint, apex, point of contact, and finish (as well as information about the current golfer's handicapp, tendancies, and the outcome of the shot), Tinker using clustering algorithms and neural networks to assign the golfer to one of n number of swing prototypes and offers personalized suggestions, drills, and tips that are ranked based on what is most likely to improve the golfer's scores and align them with their swing prototype. 


## How does this accomplishment transform the golf coaching space?

At Tinker, we promise to do the tinkering for you. While we would eventually like to revolutionize the way coaching is done in all sports, our current goal is to help all golfers maximize their potential, get the absolute most out of their practice time, and do so at a low cost. Tinker will revolutionize the way players talk about their swings and the ways that they go about improving them. It is hard enough finding the time to practice; at Tinker, we'll make sure that you don’t waste that time when you actually have it.
